export default {
    수험번호: 'no',
    군: 'gun',
    캠퍼스: 'campus',
    전형: 'type',
    모집단위: 'modan',
    모집단위코드: 'modan_code',
    주야: 'day',
    이름: 'name',
    주민등록번호: 'jumin',
    전화: 'phone',
    핸드폰: 'cellphone',
    이메일: 'email',
    고교명: 'high',
    고교코드: 'high_code',
    고교졸업일: 'graduated',
    졸업상태: 'state',
    UseHsb: 'use_hsb',
    접수시간: 'receipted',
}
